In [1]:
library(dplyr)
matches <- readr::read_csv('results.csv')

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Parsed with column specification:
cols(
  date = col_date(format = ""),
  home_team = col_character(),
  away_team = col_character(),
  home_score = col_integer(),
  away_score = col_integer(),
  tournament = col_character(),
  city = col_character(),
  country = col_character(),
  neutral = col_logical()
)

In [2]:
matches %>%
  select(date, home_team, away_team, home_score, away_score) %>%
  mutate(total_goals = home_score + away_score) %>%
  arrange(-total_goals) %>%
  head(1)

  date       home_team away_team      home_score away_score total_goals
1 2001-04-11 Australia American Samoa 31         0          31

Creation of new data frame with unique names of countries.

In [3]:
teams <- data.frame(team = unique(c(matches$home_team, matches$away_team)))

In [5]:
teams

    team
1   Scotland
2   England
3   Wales
4   Northern Ireland
5   USA
6   Uruguay
7   Austria
8   Hungary
9   Argentina
10  Belgium
11  France
12  Netherlands
13  Czechoslovakia
14  Switzerland
15  Sweden
16  Germany
17  Italy
18  Chile
19  Norway
20  Finland
21  Luxembourg
22  Russia
23  Denmark
24  Brazil
25  Japan
26  Paraguay
27  Canada
28  Estonia
29  Costa Rica
30  Guatemala
⋮   ⋮
215 Czech Republic
216 Guernsey
217 Macedonia
218 Jersey
219 Montserrat
220 Serbia
221 Bosnia-Herzegovina
222 Maldives
223 Andorra
224 British Virgin Islands
225 Virgin Islands
226 Eritrea
227 Bahamas
228 Micronesia FS
229 Bhutan
230 Monaco
231 Gibraltar
232 Tuvalu
233 Mayotte
234 Turks and Caicos Islands
235 East Timor
236 Kosovo
237 Northern Mariana Islands
238 Comoros
239 Bonaire
240 South Sudan
241 St. Pierre & Miquelon
242 Western Australia
243 Tibet
244 Vatican

In [6]:
teams <- teams %>%
  mutate(elo = 1500)

In [7]:
teams

    team                     elo
1   Scotland                 1500
2   England                  1500
3   Wales                    1500
4   Northern Ireland         1500
5   USA                      1500
6   Uruguay                  1500
7   Austria                  1500
8   Hungary                  1500
9   Argentina                1500
10  Belgium                  1500
11  France                   1500
12  Netherlands              1500
13  Czechoslovakia           1500
14  Switzerland              1500
15  Sweden                   1500
16  Germany                  1500
17  Italy                    1500
18  Chile                    1500
19  Norway                   1500
20  Finland                  1500
21  Luxembourg               1500
22  Russia                   1500
23  Denmark                  1500
24  Brazil                   1500
25  Japan                    1500
26  Paraguay                 1500
27  Canada                   1500
28  Estonia                  1500
29  Costa Rica               1500
30  Guatemala                1500
⋮   ⋮                        ⋮
215 Czech Republic           1500
216 Guernsey                 1500
217 Macedonia                1500
218 Jersey                   1500
219 Montserrat               1500
220 Serbia                   1500
221 Bosnia-Herzegovina       1500
222 Maldives                 1500
223 Andorra                  1500
224 British Virgin Islands   1500
225 Virgin Islands           1500
226 Eritrea                  1500
227 Bahamas                  1500
228 Micronesia FS            1500
229 Bhutan                   1500
230 Monaco                   1500
231 Gibraltar                1500
232 Tuvalu                   1500
233 Mayotte                  1500
234 Turks and Caicos Islands 1500
235 East Timor               1500
236 Kosovo                   1500
237 Northern Mariana Islands 1500
238 Comoros                  1500
239 Bonaire                  1500
240 South Sudan              1500
241 St. Pierre & Miquelon    1500
242 Western Australia        1500
243 Tibet                    1500
244 Vatican                  1500

In [8]:
matches <- matches %>%
  mutate(result = if_else(home_score > away_score, 1,
                          if_else(home_score == away_score, 0.5, 0)))

In [9]:
matches

      date       home_team        away_team          home_score away_score
1     1872-11-30 Scotland         England            0           0
2     1873-03-08 England          Scotland           4           2
3     1874-03-07 Scotland         England            2           1
4     1875-03-06 England          Scotland           2           2
5     1876-03-04 Scotland         England            3           0
6     1876-03-25 Scotland         Wales              4           0
7     1877-03-03 England          Scotland           1           3
8     1877-03-05 Wales            Scotland           0           2
9     1878-03-02 Scotland         England            7           2
10    1878-03-23 Scotland         Wales              9           0
11    1879-01-18 England          Wales              2           1
12    1879-04-05 England          Scotland           5           4
13    1879-04-07 Wales            Scotland           0           3
14    1880-03-13 Scotland         England            5           4
15    1880-03-15 Wales            England            2           3
16    1880-03-27 Scotland         Wales              5           1
17    1881-02-26 England          Wales              0           1
18    1881-03-12 England          Scotland           1           6
19    1881-03-14 Wales            Scotland           1           5
20    1882-02-18 Northern Ireland England            0          13
21    1882-02-25 Wales            Northern Ireland   7           1
22    1882-03-11 Scotland         England            5           1
23    1882-03-13 Wales            England            5           3
24    1882-03-25 Scotland         Wales              5           0
25    1883-02-03 England          Wales              5           0
26    1883-02-24 England          Northern Ireland   7           0
27    1883-03-10 England          Scotland           2           3
28    1883-03-12 Wales            Scotland           0           3
29    1883-03-17 Northern Ireland Wales              1           1
30    1884-01-26 Northern Ireland Scotland           0           5
⋮     ⋮          ⋮                ⋮                  ⋮          ⋮
38965 2018-05-31 Romania          Chile              3          2
38966 2018-05-31 Luxembourg       Senegal            0          0
38967 2018-05-31 Mozambique       Seychelles         2          1
38968 2018-05-31 Comoros          Madagascar         0          1
38969 2018-05-31 Slovakia         Netherlands        1          1
38970 2018-06-01 France           Italy              3          1
38971 2018-06-01 Turkey           Tunisia            2          2
38972 2018-06-01 Korea Republic   Bosnia-Herzegovina 1          3
38973 2018-06-01 Czech Republic   Australia          0          4
38974 2018-06-01 Algeria          Cape Verde         2          3
38975 2018-06-01 Colombia         Egypt              0          0
38976 2018-06-01 Malta            Georgia            0          1
38977 2018-06-01 Botswana         Mauritius          6          0
38978 2018-06-01 Angola           Malawi             0          0
38979 2018-06-01 India            Taiwan             5          0
38980 2018-06-02 El Salvador      Honduras           1          0
38981 2018-06-02 Thailand         China              0          2
38982 2018-06-02 England          Nigeria            2          1
38983 2018-06-02 Montenegro       Slovenia           0          2
38984 2018-06-02 Mexico           Scotland           1          0
38985 2018-06-02 Sweden           Denmark            0          0
38986 2018-06-02 Ireland          USA                2          1
38987 2018-06-02 Belgium          Portugal           0          0
38988 2018-06-02 Austria          Germany            2          1
38989 2018-06-02 Niger            Uganda             2          1
38990 2018-06-02 Iceland          Norway             2          3
38991 2018-06-02 Zambia           Namibia            0          0
38992 2018-06-02 Lesotho          Swaziland          1          0
38993 2018-06-02 Latvia           Estonia            1          0
38994 2018-06-02 Kenya            New Zealand        2          1
      tournament           city         country        neutral result
1     Friendly             Glasgow      Scotland       FALSE   0.5
2     Friendly             London       England        FALSE   1.0
3     Friendly             Glasgow      Scotland       FALSE   1.0
4     Friendly             London       England        FALSE   0.5
5     Friendly             Glasgow      Scotland       FALSE   1.0
6     Friendly             Glasgow      Scotland       FALSE   1.0
7     Friendly             London       England        FALSE   0.0
8     Friendly             Wrexham      Wales          FALSE   0.0
9     Friendly             Glasgow      Scotland       FALSE   1.0
10    Friendly             Glasgow      Scotland       FALSE   1.0
11    Friendly             London       England        FALSE   1.0
12    Friendly             London       England        FALSE   1.0
13    Friendly             Wrexham      Wales          FALSE   0.0
14    Friendly             Glasgow      Scotland       FALSE   1.0
15    Friendly             Wrexham      Wales          FALSE   0.0
16    Friendly             Glasgow      Scotland       FALSE   1.0
17    Friendly             Blackburn    England        FALSE   0.0
18    Friendly             London       England        FALSE   0.0
19    Friendly             Wrexham      Wales          FALSE   0.0
20    Friendly             Belfast      Ireland        FALSE   0.0
21    Friendly             Wrexham      Wales          FALSE   1.0
22    Friendly             Glasgow      Scotland       FALSE   1.0
23    Friendly             Wrexham      Wales          FALSE   1.0
24    Friendly             Glasgow      Scotland       FALSE   1.0
25    Friendly             London       England        FALSE   1.0
26    Friendly             Liverpool    England        FALSE   1.0
27    Friendly             Sheffield    England        FALSE   0.0
28    Friendly             Wrexham      Wales          FALSE   0.0
29    Friendly             Belfast      Ireland        FALSE   0.5
30    British Championship Belfast      Ireland        FALSE   0.0
⋮     ⋮                    ⋮            ⋮              ⋮       ⋮
38965 Friendly             Graz         Austria         TRUE   1.0
38966 Friendly             Luxembourg   Luxembourg     FALSE   0.5
38967 COSAFA Cup           Polokwane    South Africa    TRUE   1.0
38968 COSAFA Cup           Polokwane    South Africa    TRUE   0.0
38969 Friendly             Trnava       Slovakia       FALSE   0.5
38970 Friendly             Nice         France         FALSE   1.0
38971 Friendly             Geneva       Switzerland     TRUE   0.5
38972 Friendly             Jeonju       Korea Republic FALSE   0.0
38973 Friendly             Sankt Pölten Austria         TRUE   0.0
38974 Friendly             Algiers      Algeria        FALSE   0.0
38975 Friendly             Bergamo      Italy           TRUE   0.5
38976 Friendly             Schwaz       Austria         TRUE   0.0
38977 COSAFA Cup           Polokwane    South Africa    TRUE   1.0
38978 COSAFA Cup           Polokwane    South Africa    TRUE   0.5
38979 Friendly             Mumbai       India          FALSE   1.0
38980 Friendly             Houston      USA             TRUE   1.0
38981 Friendly             Bangkok      Thailand       FALSE   0.0
38982 Friendly             London       England        FALSE   1.0
38983 Friendly             Podgorica    Montenegro     FALSE   0.0
38984 Friendly             Mexico City  Mexico         FALSE   1.0
38985 Friendly             Solna        Sweden         FALSE   0.5
38986 Friendly             Dublin       Ireland        FALSE   1.0
38987 Friendly             Brussels     Belgium        FALSE   0.5
38988 Friendly             Klagenfurt   Austria        FALSE   1.0
38989 Friendly             Niamey       Niger          FALSE   1.0
38990 Friendly             Reykjavík    Iceland        FALSE   0.0
38991 COSAFA Cup           Polokwane    South Africa    TRUE   0.5
38992 COSAFA Cup           Polokwane    South Africa    TRUE   1.0
38993 Baltic Cup           Riga         Latvia         FALSE   1.0
38994 Friendly             Mumbai       India           TRUE   1.0

In [10]:
matches <- matches %>%
  select(date, home_team, away_team, result) %>%
  arrange(date)

In [11]:
matches

      date       home_team        away_team          result
1     1872-11-30 Scotland         England            0.5
2     1873-03-08 England          Scotland           1.0
3     1874-03-07 Scotland         England            1.0
4     1875-03-06 England          Scotland           0.5
5     1876-03-04 Scotland         England            1.0
6     1876-03-25 Scotland         Wales              1.0
7     1877-03-03 England          Scotland           0.0
8     1877-03-05 Wales            Scotland           0.0
9     1878-03-02 Scotland         England            1.0
10    1878-03-23 Scotland         Wales              1.0
11    1879-01-18 England          Wales              1.0
12    1879-04-05 England          Scotland           1.0
13    1879-04-07 Wales            Scotland           0.0
14    1880-03-13 Scotland         England            1.0
15    1880-03-15 Wales            England            0.0
16    1880-03-27 Scotland         Wales              1.0
17    1881-02-26 England          Wales              0.0
18    1881-03-12 England          Scotland           0.0
19    1881-03-14 Wales            Scotland           0.0
20    1882-02-18 Northern Ireland England            0.0
21    1882-02-25 Wales            Northern Ireland   1.0
22    1882-03-11 Scotland         England            1.0
23    1882-03-13 Wales            England            1.0
24    1882-03-25 Scotland         Wales              1.0
25    1883-02-03 England          Wales              1.0
26    1883-02-24 England          Northern Ireland   1.0
27    1883-03-10 England          Scotland           0.0
28    1883-03-12 Wales            Scotland           0.0
29    1883-03-17 Northern Ireland Wales              0.5
30    1884-01-26 Northern Ireland Scotland           0.0
⋮     ⋮          ⋮                ⋮                  ⋮
38965 2018-05-31 Romania          Chile              1.0
38966 2018-05-31 Luxembourg       Senegal            0.5
38967 2018-05-31 Mozambique       Seychelles         1.0
38968 2018-05-31 Comoros          Madagascar         0.0
38969 2018-05-31 Slovakia         Netherlands        0.5
38970 2018-06-01 France           Italy              1.0
38971 2018-06-01 Turkey           Tunisia            0.5
38972 2018-06-01 Korea Republic   Bosnia-Herzegovina 0.0
38973 2018-06-01 Czech Republic   Australia          0.0
38974 2018-06-01 Algeria          Cape Verde         0.0
38975 2018-06-01 Colombia         Egypt              0.5
38976 2018-06-01 Malta            Georgia            0.0
38977 2018-06-01 Botswana         Mauritius          1.0
38978 2018-06-01 Angola           Malawi             0.5
38979 2018-06-01 India            Taiwan             1.0
38980 2018-06-02 El Salvador      Honduras           1.0
38981 2018-06-02 Thailand         China              0.0
38982 2018-06-02 England          Nigeria            1.0
38983 2018-06-02 Montenegro       Slovenia           0.0
38984 2018-06-02 Mexico           Scotland           1.0
38985 2018-06-02 Sweden           Denmark            0.5
38986 2018-06-02 Ireland          USA                1.0
38987 2018-06-02 Belgium          Portugal           0.5
38988 2018-06-02 Austria          Germany            1.0
38989 2018-06-02 Niger            Uganda             1.0
38990 2018-06-02 Iceland          Norway             0.0
38991 2018-06-02 Zambia           Namibia            0.5
38992 2018-06-02 Lesotho          Swaziland          1.0
38993 2018-06-02 Latvia           Estonia            1.0
38994 2018-06-02 Kenya            New Zealand        1.0

In [12]:
head(teams)

  team             elo
1 Scotland         1500
2 England          1500
3 Wales            1500
4 Northern Ireland 1500
5 USA              1500
6 Uruguay          1500

In [13]:
library(elo)

ERROR: Error in library(elo): there is no package called ‘elo’